appbook_index:
  path: /
  defaults: { _controller: AppBookBundle:Index:index }

appbook_book_add:
    path:    /ajouter/livre
    defaults: { _controller: AppBookBundle:Book:add }

appbook_genre_add:
    path:    /ajouter/genre
    defaults: { _controller: AppBookBundle:Genre:add }

appbook_author_add:
    path:    /ajouter/auteur
    defaults: { _controller: AppBookBundle:Author:add }
