appbook_index:
  path: /
  defaults: { _controller: AppBookBundle:Index:index }

appbook_book_add:
    path:    /livre/ajouter
    defaults: { _controller: AppBookBundle:Book:add }

appbook_genre_add:
    path:    /genre/ajouter
    defaults: { _controller: AppBookBundle:Genre:add }

appbook_author_add:
    path:    /auteur/ajouter
    defaults: { _controller: AppBookBundle:Author:add }
